# Generated by Django 2.2.5 on 2020-05-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_auto_20200511_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='tel_no',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
