# Generated by Django 2.2.5 on 2020-05-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('name', models.CharField(max_length=50)),
                ('tel_no', models.CharField(max_length=6)),
                ('mobile', models.CharField(max_length=10)),
                ('mail', models.EmailField(max_length=254)),
                ('plan_id', models.CharField(max_length=10)),
            ],
        ),
    ]
