# Generated by Django 2.2.5 on 2020-05-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_auto_20200511_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='id',
        ),
        migrations.AlterField(
            model_name='customers',
            name='tel_no',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
