# Generated by Django 2.2.5 on 2020-05-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0009_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_acitve',
            field=models.BooleanField(default=True),
        ),
    ]
