# Generated by Django 2.2.5 on 2020-05-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0010_plan_is_acitve'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=20),
        ),
    ]
