# Generated by Django 2.2.5 on 2020-05-12 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0011_customers_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='is_acitve',
            new_name='is_active',
        ),
    ]
