# Generated by Django 2.2.5 on 2020-05-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0012_auto_20200512_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='status',
            field=models.CharField(default='DEACTIVATE', max_length=20),
        ),
    ]
